### ISSUE TITLE
Mousing over Categories keeps it open. 

### ISSUE THREAD

**Issue by rcaloras** [gilt/tech-blog#18]
Mousing over the categories opens the dropdown, but when you mouse out it stays open until you click back on the page. It should close on mouse out. 

![image](https://cloud.githubusercontent.com/assets/149818/10126036/788511b2-6556-11e5-9e90-0d065d6f1b98.png)

**Comment by shellscape** [comment]
would happily welcome a pull request

**Comment by rcaloras** [comment]
Not perfect, but better. Last time I had to make mouse over dropdowns I think I used a before tag to create a small bit of runway between the anchor and the menu.

**Comment by rcaloras** [comment]
Closed with https://github.com/gilt/tech-blog/pull/19
