### ISSUE TITLE
Double Categories showing up on posts

### ISSUE THREAD

**Issue by heatherfleming** [gilt/tech-blog#3]
Added in some categories on posts today and they're showing up twice:

http://code.gilt.com/tech-blog/analytics/2015/05/11/importing-google-trends-data/
http://code.gilt.com/tech-blog/solr/2015/05/14/last-chance-to-join-the-meetup-tonight/
http://code.gilt.com/tech-blog/agile/2015/05/19/is-agile-a-competitive-advantage/

**Comment by shellscape** [comment]
it seems that when you populate 'category: analytics' it also populates an internal variable called 'categories'. As a recommendation, I'd stick with 'categories' plural, even if you're only listing one. I'll make a change in the template so you can use either, but I'd rather standardize on 'categories' plural so we have a fairly common front-matter section across posts.
